config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :decks do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: :index

  get "my-decks", to: "decks#my_decks", as: :my_decks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :deck

validates :date_of_beginning, presence: true
validates :date_of_end, presence: true
validate :date_of_end_after_date_of_beginning

private

def date_of_end_after_date_of_beginning
  return if date_of_end.blank? || date_of_beginning.blank?

  if date_of_end < date_of_beginning
    errors.add(:date_of_end, "must be after the start date")
  end
end
end

app/models/card.rb
class Card < ApplicationRecord
  has_one_attached :photo

  has_many :deck_cards
  has_many :decks, through: :deck_cards

  validates :name, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user

  has_many :bookings
  has_many :users, through: :bookings
  has_many :deck_cards
  has_many :cards, through: :deck_cards

  has_one_attached :photo

  validates :title, presence: true
end

app/models/deck_card.rb
class DeckCard < ApplicationRecord
  belongs_to :deck
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :decks, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])

    # For additional fields in app/views/devise/sessions/new.html.erb
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_deck, only: %i[new create]
  def index
    @bookings = filter_bookings(Booking.all)
    # @bookings = Booking.where("user_id = ?", @user.id)
    @booking = Booking.new
  end

  def new; end

  def create
    @booking = Booking.new(booking_params)

    @booking.user = current_user
    @booking.deck = @deck

    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def filter_bookings(bookings)
    bookings.select { |booking| booking.user == current_user}
  end

  def set_deck
    @deck = Deck.find(params[:deck_id])
  end

  def booking_params
    params.require(:booking).permit(:date_of_beginning, :date_of_end)
  end
end

app/controllers/decks_controller.rb
require "open-uri"

class DecksController < ApplicationController
  before_action :set_deck, only: %i[show edit update destroy]
  before_action :set_cards, only: %i[new edit]
  skip_before_action :authenticate_user!, only: %i[index show]

  # See others decks
  def index
    @decks = Deck.all
    @decks = search_decks(@decks) if params[:query].present?
    @decks = others_decks(@decks) unless current_user.nil?
  end

  # See self decks
  def my_decks
    @decks = Deck.all
    @decks = self_decks(@decks)
  end

  def show
    @booking = Booking.new
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user

    if @deck.save
      save_deck_cards
      redirect_to deck_path(@deck)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @deck.update(deck_params)
      redirect_to deck_path(@deck)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @deck.destroy
    redirect_to my_decks_path, status: :see_other
  end

  private

  def set_cards
    @cards = Card.all
  end

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:title, :description, :price)
  end

  def save_deck_cards
    ids = params[:deck][:card_ids].map { |element| element.to_i }
    ids.delete_at(0)
    cards = ids.map { |id| Card.find(id) }
    cards.each do |card|
      DeckCard.create(deck_id: @deck.id, card_id: card[:id])
    end
    cloudinary_url = @deck.cards.first.photo.url
    file = URI.parse(cloudinary_url).open

    @deck.photo.attach(io: file, filename: "pokemon")
  end

  def self_decks(decks)
    decks.select { |deck| deck.user.username == current_user.username }
  end

  def others_decks(decks)
    decks.reject { |deck| deck.user.username == current_user.username }
  end

  def search_decks(decks)
    sql_subquery = <<~SQL
      decks.title @@ :query
      OR decks.description @@ :query
      OR cards.name @@ :query
    SQL
    decks.joins(:cards).where(sql_subquery, query: "%#{params[:query]}%").distinct
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    decks = Deck.all.sample(50)
    shuffled_decks = decks.shuffle

    @decks1 = shuffled_decks.first(3)
    @decks2 = shuffled_decks.last(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <div>
  <h1>Rent a deck</h1>
  <h2><%= @deck.title %></h2>

  <div class="row">

    <div class="col-6">
      <img src="" alt="">
    </div>

    <div class="col-6">
      <%= simple_form_for [@deck, @booking], data: { insert_in_list_target: "form" } do |f| %>
      <%= f.input :date_of_beginning,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :date_of_end,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
      <%# f.input :date_of_beginning, as: :date %>
      <%# f.input :date_of_end, as: :date %>

      <div class="btn btn-primary">
        <%= f.button :submit %>
      </div>

      <% end %>
    </div>
  </div>
  <div>
  </div>
    <h2>Decks cards</h2>
      <ul>
        <% @deck.cards.each do |card| %>
          <li><%= cl_image_tag card.photo.key %></li>
        <% end %>
      </ul>

      <%#
        <div class="card" style="width: 18rem;">
          <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Pokémon</h5>
          </div>
        </div>
      %>

  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center my-4" style="font-family: 'Press Start 2P', cursive;"><strong>Your bookings</strong></h1>
      <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
      <% @bookings.each do |booking| %>
        <div class="row justify-content-center mb-3">
            <div class="card text-center" style="border: 1px solid #ff6b6b; width: 32rem; border-radius: 10px;">
            <div class="card-body d-flex justify-content-between align-items-center">
              <h6 class="card-title mb-0" style="font-family: 'Press Start 2P', cursive; font-size: 14px;"><strong><%= booking.deck.title %></strong></h6>
              <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
              <div class="text-right">
              <p class="card-text mb-1">from: <%= booking.date_of_beginning %></p>
              <p class="card-text mb-0">until: <%= booking.date_of_end %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%# <h1>Welcome to the new world</h1>

<%= render "form" %>

app/views/decks/_deck_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :price, label: "Price" %>

  <%= f.association :cards,
                    as: :check_boxes,
                    as: :check_boxes,
                    input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>

  <%= f.button :submit, class: "btn btn-flat" %>
<% end %>

app/views/decks/_display.html.erb
<div class="container container-deck">
  <div class="container">
    <div class="col-12">
      <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="row">
          <div class="col-6">
            <%= link_to "Back", root_path, class: "btn btn-flat" %>
          </div>
          <% if type == "mine" %>
            <div class="button-before-footer col-6">
              <%= link_to "New", new_deck_path,class: "btn btn-flat" %>
            </div>
          <% end %>
        </div>

        <div class="d-flex " >
          <%= form_with url: decks_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query, params[:query], class: "form-control btn-flat2-input" , placeholder: "Find a deck" %>
            <%= submit_tag "Search", name: "", class: "btn btn-flat2 ms-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <% @decks.each do |deck| %>
      <div class="col-sm-4 my-3">
        <div class="card h-100 card-trip2">
          <%= link_to deck_path(deck) do %>
            <%= cl_image_tag deck.photo.key, class: "card-img-top" %>
          <% end %>
          <div class="card-body ">
            <h5 class="card-title"><%= deck.title %></h5>
          </div>
          <div class="card-footer card-trip-creator">
            <small class="text-body-secondary">Created by: <%= deck.user.username %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/decks/_form.html.erb
<div class="container">

    <div class="row p-3 no-gutter form-container">

      <div class="col-6 d-flex justify-content-center">
        <div><%= cl_image_tag @deck.photo.key, class: "img-fluid", height: 450, crop: :fill %></div>
      </div>

      <div class="col-6">

          <div class="col-12">

            <div class="col-12">
                <h2 class="deck-title"><%= @deck.title %></h2>
            </div>

            <div class="row d-flex gap-2">
              <p class="col-4 tag-owner">Owner : <%= @deck.user.username %></p>
              <p class="col-4 tag-owner">Price per day : <%= @deck.price %>€<p>
            </div>

            <div class="col-4">
            </div>

            <div>
              <p><%= @deck.description %></p>
            </div>

            <div class="align-self-end">

              <% if current_user %>
              <%= simple_form_for [@deck, @booking] do |f| %>
              <div data-controller = "datepicker">
                <div class="row">
                  <div class="col-6">
                    <div class="mt-4">
                          <%= f.input :date_of_beginning, label: "From", as: :string, input_html: { data: { datepicker_target: "start" } } %>
                          <%= f.input :date_of_end, as: :hidden, input_html: { data: { datepicker_target: "end" } } %>
                    </div>
                  </div>
                          <div class="col-6 d-flex align-items-bottom">
                          <div class="row pt-5">
                            <div class="pt-2">
                              <h6 class="price">Total : <span class="">30 €</span></h6>
                            </div>
                          </div>
                          </div>
                </div>
              </div>


              <div class="col-6 d-flex align-items-center">
                <div class="col-12 d-flex align-item-baseline pt-3">
                  <%= f.submit "Book now", class:"p-submit col-12 btn-flat"%>
                </div>
              </div>

            </div>

          <% end %>
          </div>
      <% end %>
    </div>


  </div>
</div>

app/views/decks/edit.html.erb
<div class="container">
  <%= render "deck_form" %>
</div>

app/views/decks/index.html.erb
<%= render "display", type: "others" %>
<%# style="max-width: 1200px; margin: 0 auto;" %>

app/views/decks/my_decks.html.erb
<%= render "display", type: "mine" %>

app/views/decks/new.html.erb
<div class="container">
  <div class="d-flex pb-2 m-2">
    <%= link_to "Back", my_decks_path, class: "btn btn-flat" %>
  </div>
<div class="form-container p-5 m-2">
  <h2 class="form-title">Create your deck!!</h2>
  <%= render "deck_form" %>

</div>

</div>

app/views/decks/show.html.erb
<div class="container mt-4">
  <div class="mb-2"><%= link_to "Back", decks_path, class: "btn btn-flat col-1 mt-1 mb-1" %> </div>
    <div>
      <%= render "form", booking: @booking %>
    </div>

    <div class="container mt-3 form-container">
      <h2 >Deck cards</h2>
      <ul class="list-group d-flex flex-row flex-wrap list-group-flush">
        <% @deck.cards.each do |card| %>
          <li class="list-group-item col-3 index-deck-container p-4"><%= cl_image_tag card.photo.key, class: "img-fluid", height: 450, crop: :fill %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
  </head>


  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <main id="main-content">
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=asset_path('1.jpg') %>);">
  <div class="container">
    <h1><%= image_tag("pokebnb-logo.png", width: 350, height: 180) %></h1>
    <p><strong>Loue ton deck, domine les tournois!</strong></p>
    <div class="button-container">
      <%= link_to "Louer un deck", decks_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

<h2>"Découvrez nos derniers decks exclusifs et boostez vos performances !"</h2>

<div class="box container">
  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="cards d-flex" alt="First slide">
          <% @decks1.each do |deck| %>
            <div class="card-trip">
              <div><h4><%= deck.title %></h4></div>
              <%= link_to deck_path(deck) do %>
                <%= cl_image_tag(deck.photo.key, class: "d-block w-100", height: 400, crop: :fill) %>
                <div class="card-trip-infos">
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="carousel-item">
        <div class="cards  d-flex" alt="Second slide">
          <% @decks2.each do |deck| %>
            <div class="card-trip">
              <div><h4><%= deck.title %></h4></div>
              <%= link_to deck_path(deck) do %>
                <%= cl_image_tag(deck.photo.key, class: "d-block w-100", height: 400, crop: :fill) %>
                <div class="card-trip-infos">
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

<%# <div class="button-before-footer">
  <%= link_to "View more Decks", decks_path, class: "btn btn-flat" %>
<%# </div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#">Contact</a>
  </div>
  <div class="footer-copyright">
    © 2025 All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'pokebnb-logo.png' %>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "#", class: "nav-link" do %>
              <i class="fa-solid fa-house"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "#", class: "nav-link" do %>
              <i class="fa-solid fa-cart-shopping"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Decks", my_decks_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>